### ISSUE TITLE
Issue with pry rails prompt

### ISSUE THREAD

**Issue by matthutchinson** [rweng/pry-rails#118]
I'm seeing:

> warning: `Pry::Prompt[:rails][:value]` is deprecated. Use `Pry::Prompt#prompt_procs` instead or an instance of `Pry::Prompt` directly
> warning: setting prompt with help of `Pry.config.prompt = [proc {}, proc {}]` is deprecated. Use Pry::Prompt API instead

* pry (0.13.0)
* pry-rails (0.3.9)

My ~/.pryrc 

    if Pry::Prompt[:rails]
      Pry.config.prompt = Pry::Prompt[:rails][:value]
    end

From the pry docs/code its not clear how to resolve this.

**Comment by CHTJonas** [comment]
According to https://github.com/pry/pry/pull/1877 it should be:

```ruby
if Pry::Prompt[:rails]
  Pry.config.prompt = Pry::Prompt[:rails]
end
```

**Comment by matthutchinson** [comment]
Thanks for digging that out, its not mentioned in any docs I could find.

**Comment by CHTJonas** [comment]
Yeah it's surprisingly well hidden. I'll open a PR and see about getting the README here changed.
