### ISSUE TITLE
Using Pry inside a Rails engine.

### ISSUE THREAD

**Issue by ptrhvns** [rweng/pry-rails#25]
It looks like `pry-rails` does not work within a Rails engine. The following commands were run in a "gemified" Rails 3.2.6 engine, with RSpec 2.11.0, and where the `spec/dummy` directory contains the dummy application to run tests against:

```
$ grep ^gemspec Gemfile
gemspec

$ grep pry ${engine_name}.gemspec 
  s.add_development_dependency 'pry-rails', '~> 0.1.6'

$ (cd spec/dummy; rails console)
Loading development environment (Rails 3.2.6)
irb(main):001:0>
```

**Comment by bparanj** [comment]
You cannot use pry gem in any group. We should be able to group it under test and development. This is still a bug.

**Comment by adisos** [comment]
I can confirm. It's not working with groups.
