### ISSUE TITLE
using bundler :console group

### ISSUE THREAD

**Issue by jjb** [rweng/pry-rails#27]
I use the method described here in the "Console Extensions" section to only load pry and pry rails when i'm firing up the console (so I can have it on production without loading it into memory for my app).

  http://iain.nl/getting-the-most-out-of-bundler-groups#toc_5

This worked with 0.1.6, but now with 0.2.1 pry no longer loads in any environment. If i take it out of the :console group it does load as expected.

I poked around in the pry-rails railtie and other code and couldn't really see what might be happening, figured I'd raise it here before spending an hour learning pry-rails :-)

Thanks for a great project!

**Comment by markquezada** [comment]
@jjb Did you ever get this working? Running into the exact same issue now, years later ;)
