### ISSUE TITLE
pry-rails gives odd warnings with rails4

### ISSUE THREAD

**Issue by Trevoke** [rweng/pry-rails#49]
I get the following message:

```
→ rails c
Loading development environment (Rails 4.0.1)
[WARN] cannot load Rails console commands (Not on Rails2 or Rails3?)

Frame number: 0/3
[1] pry(main)>
```

Even doing it this way in application.rb without pry-rails, I get the same warnings:

``` ruby
console do
  require "pry"
  config.console = Pry
end
```

Taken from http://stackoverflow.com/questions/19151801/pry-rails-not-rails-console-working-with-rails-4-0

**Comment by civrot** [comment]
@Trevoke I am getting the same message on a brand new app.  What what obsolete config files you mentioned?

**Comment by rf-** [comment]
Everything past the first three lines in this file should not be used with pry-rails: https://gist.github.com/bsodmike/5125150

**Comment by civrot** [comment]
I got it just before you posted that, and I was about to comment. I just removed my .pryrc and it works just fine now.  woo hoo!
