### ISSUE TITLE
Add an option to the `rails c` command, to launch the console without pry

### ISSUE THREAD

**Issue by petrachi** [rweng/pry-rails#62]
When using the `pry-rails` gem, the rails console is always launch with pry.

I think it would be great to have an option to the `rails c` command, or an command with an other name, that launch the default rails console (ie: without pry).

It is useful sometimes, because pry is sometimes not the best option in the console. For example, when you work with long arrays/hashes. It also hide the ruby backtrace.

What do you think of this ?

**Comment by petrachi** [comment]
Ok, didn't knew we could do that.
Is it somewhere in the docs ? Maybe it could be nice to add that information.

Thanks!

(I let you close this issue)

**Comment by rf-** [comment]
It is in the README, kind of, but could definitely be clearer (it's at the end of the example).
