### ISSUE TITLE
Misleading repo description

### ISSUE THREAD

**Issue by vfonic** [rweng/pry-rails#77]
Hi,

The repo description says:
> Rails 3 pry initializer

While pry-rails works with Rails 4, too.

**Comment by rf-** [comment]
Good catch! Unfortunately I can't fix this because I don't have admin access to the repo. I think @rweng has to do it.

**Comment by rweng** [comment]
does >= work for you?

**Comment by vfonic** [comment]
Yeah, perfect! Thanks!
