### ISSUE TITLE
Crashing after installing macOS 

### ISSUE THREAD

**Issue by darrennickerson** [rweng/pry-rails#84]
After installing macOS pry crashes. 
[ruby_2016-09-27-120325_Darrens-iMac.crash.zip](https://github.com/rweng/pry-rails/files/495933/ruby_2016-09-27-120325_Darrens-iMac.crash.zip)

**Comment by rf-** [comment]
This looks like an issue with Sierra's version of `libsqlite3`. Try removing and reinstalling the `sqlite3` gem and see if that helps. This is very unlikely to be related to `pry` or `pry-rails` since it's a segfault and those gems don't use any C extensions.

**Comment by darrennickerson** [comment]
Sorry about that. The issues stopped for a few minutes when I removed the gem but has since came back. So it's nothing to do with pry.
