### ISSUE TITLE
Setting default object in rails console not working when I use pry-rails

### ISSUE THREAD

**Issue by abdul-shajin** [rweng/pry-rails#87]
When I use rails console without pry-rails, I can use `irb User` or `irb User.first` and the default object will be User/User object untill I exit from the session. It is so handy feature for me but can not use when I use pry-rails.. Any notes?

**Comment by MatthiasWinkelmann** [comment]
Create ```~/.pryrc``` with whatever initialisation you like: https://github.com/pry/pry/wiki/Pry-rc
